// Database alimenti predefinito: valori per 100 g di prodotto (per 100 ml dove indicato).
// Ogni riga: [nome, macro principale, carboidrati, proteine, grassi]
// Il "macro principale" serve per le sostituzioni e le conversioni tra alimenti equivalenti;
// i totali della dieta usano sempre tutti e tre i macronutrienti.
// Le calorie si calcolano come 4 kcal/g carboidrati, 4 kcal/g proteine, 9 kcal/g grassi.
// Valori medi da tabelle nutrizionali (CREA, USDA) ed etichette tipiche: i prodotti reali possono variare.
const FOOD_TABLE = [
  // ==========================================
  // CARBOIDRATI
  // ==========================================
  // Pasta e Gnocchi
  ["Pasta di Semola", "Carboidrati", 73, 13, 1.5],
  ["Pasta Integrale", "Carboidrati", 65, 13, 2.5],
  ["Pasta all'Uovo", "Carboidrati", 68, 13, 4],
  ["Pasta di Riso", "Carboidrati", 80, 7, 1],
  ["Pasta di Mais", "Carboidrati", 79, 7, 1.5],
  ["Pasta di Farro", "Carboidrati", 67, 14, 2],
  ["Pasta di Lenticchie/Piselli", "Carboidrati", 50, 24, 2],
  ["Gnocchi di Patate (confezionati)", "Carboidrati", 32, 4.5, 0.4],
  ["Pasta di Kamut (Khorasan)", "Carboidrati", 68, 14, 2],
  ["Pasta di Ceci", "Carboidrati", 47, 21, 6],
  ["Pasta Senza Glutine (Mais e Riso)", "Carboidrati", 78, 6, 1.5],
  // Riso e Cereali
  ["Riso Basmati", "Carboidrati", 78, 8, 0.6],
  ["Riso Carnaroli / Arborio", "Carboidrati", 80, 7, 0.5],
  ["Riso Integrale", "Carboidrati", 74, 7.5, 2.5],
  ["Riso Venere (Nero)", "Carboidrati", 72, 8, 2.8],
  ["Riso Rosso", "Carboidrati", 74, 7.5, 2.5],
  ["Avena (Fiocchi)", "Carboidrati", 60, 13, 7],
  ["Farina di Avena", "Carboidrati", 60, 13, 7],
  ["Farro Perlato", "Carboidrati", 67, 15, 2.5],
  ["Orzo Perlato", "Carboidrati", 70, 10, 1.4],
  ["Quinoa", "Carboidrati", 64, 14, 6],
  ["Cous Cous", "Carboidrati", 77, 12, 1.5],
  ["Grano Saraceno", "Carboidrati", 71, 12, 3],
  ["Polenta (Farina di Mais)", "Carboidrati", 75, 8, 2.5],
  ["Cornflakes (classici)", "Carboidrati", 81, 7.5, 0.9],
  ["Riso Parboiled", "Carboidrati", 79, 7.5, 0.6],
  ["Riso Jasmine", "Carboidrati", 79, 7, 0.6],
  ["Riso Basmati Integrale", "Carboidrati", 75, 8, 2.5],
  ["Riso Soffiato", "Carboidrati", 80, 7, 1.5],
  ["Miglio", "Carboidrati", 70, 11, 4],
  ["Amaranto", "Carboidrati", 60, 14, 7],
  ["Bulgur", "Carboidrati", 63, 12, 1.5],
  ["Crusca d'Avena", "Carboidrati", 49, 17, 7],
  ["Muesli (senza zuccheri aggiunti)", "Carboidrati", 60, 10, 6],
  ["Granola", "Carboidrati", 62, 9, 16],
  ["Farina 00", "Carboidrati", 74, 11, 1],
  ["Farina Integrale", "Carboidrati", 64, 13, 2.5],
  ["Semola Rimacinata", "Carboidrati", 70, 12, 1],
  ["Farina di Ceci", "Carboidrati", 54, 21, 6.5],
  ["Farina di Castagne", "Carboidrati", 76, 6, 3.7],
  // Pane e Sostituti
  ["Pane Bianco", "Carboidrati", 49, 9, 1.5],
  ["Pane Integrale", "Carboidrati", 43, 9, 2],
  ["Pane di Segale", "Carboidrati", 48, 8.5, 3.3],
  ["Pane Bauletto (industriale)", "Carboidrati", 50, 8, 4],
  ["Piadina Romagnola", "Carboidrati", 50, 8, 11],
  ["Gallette di Mais", "Carboidrati", 77, 8, 3],
  ["Gallette di Riso", "Carboidrati", 81, 8, 2.8],
  ["Fette Biscottate classiche", "Carboidrati", 72, 11.5, 6],
  ["Fette Biscottate integrali", "Carboidrati", 67, 13, 6],
  ["Taralli", "Carboidrati", 60, 9, 18],
  ["Grissini", "Carboidrati", 68, 12, 9],
  ["Crackers", "Carboidrati", 70, 10, 10],
  ["Pane di Semola (Grano Duro)", "Carboidrati", 53, 9.5, 1.2],
  ["Pane in Cassetta Integrale", "Carboidrati", 42, 10, 4.5],
  ["Pane Arabo / Pita", "Carboidrati", 55, 9, 1.2],
  ["Tortilla / Wrap", "Carboidrati", 50, 8, 7],
  ["Pane Carasau", "Carboidrati", 74, 11, 2],
  ["Friselle", "Carboidrati", 70, 12, 3],
  ["Crackers di Segale (Knäckebrot)", "Carboidrati", 61, 9.5, 1.5],
  ["Biscotti Secchi", "Carboidrati", 74, 8, 11],
  // Dolcificanti e Spalmabili
  ["Miele", "Carboidrati", 80, 0.4, 0],
  ["Marmellata / Confettura", "Carboidrati", 58, 0.4, 0.1],
  ["Zucchero", "Carboidrati", 100, 0, 0],
  ["Sciroppo d'Acero", "Carboidrati", 67, 0, 0.1],
  // Tuberi (Patate)
  ["Patate Classiche (con buccia)", "Carboidrati", 17, 2, 0.1],
  ["Patate Novelle", "Carboidrati", 15, 1.7, 0.1],
  ["Patate Dolci (Americane)", "Carboidrati", 20, 1.6, 0.1],
  ["Patate Rosse", "Carboidrati", 16, 2, 0.2],
  ["Manioca / Yuca", "Carboidrati", 38, 1.4, 0.3],
  ["Purè di Patate (fiocchi)", "Carboidrati", 76, 8, 0.5],
  ["Castagne (fresche)", "Carboidrati", 36, 3, 1.7],
  ["Mais Dolce (in scatola)", "Carboidrati", 13, 2.5, 1.2],
  // Legumi Secchi (pesati a crudo)
  ["Ceci (Secchi)", "Carboidrati", 47, 21, 6],
  ["Lenticchie (Secche)", "Carboidrati", 51, 23, 2.5],
  ["Fagioli Borlotti/Cannellini (Secchi)", "Carboidrati", 45, 22, 2],
  ["Piselli (Secchi)", "Carboidrati", 45, 22, 2],
  ["Fave (Secche)", "Carboidrati", 53, 27, 3],
  // Legumi Cotti / In scatola (sgocciolati)
  ["Ceci (In scatola)", "Carboidrati", 15, 7, 2.5],
  ["Lenticchie (In scatola)", "Carboidrati", 12, 6, 0.5],
  ["Fagioli (In scatola)", "Carboidrati", 14, 6.5, 0.5],
  ["Piselli (Surgelati/Scatola)", "Carboidrati", 10, 5.5, 0.4],
  // Frutta
  ["Banana", "Carboidrati", 23, 1.1, 0.3],
  ["Mela", "Carboidrati", 14, 0.3, 0.2],
  ["Pera", "Carboidrati", 15, 0.4, 0.1],
  ["Kiwi", "Carboidrati", 15, 1.1, 0.5],
  ["Uva", "Carboidrati", 18, 0.7, 0.2],
  ["Frutti di Bosco / Fragole", "Carboidrati", 8, 0.7, 0.4],
  ["Arancia / Mandarino", "Carboidrati", 9, 0.9, 0.2],
  ["Datteri secchi", "Carboidrati", 75, 2.5, 0.4],
  ["Uvetta / Frutta disidratata", "Carboidrati", 79, 3, 0.5],
  ["Ananas", "Carboidrati", 12, 0.5, 0.1],
  ["Pesca / Nettarina", "Carboidrati", 8, 0.9, 0.3],
  ["Albicocca", "Carboidrati", 9, 1.4, 0.4],
  ["Melone", "Carboidrati", 8, 0.8, 0.2],
  ["Anguria", "Carboidrati", 7, 0.6, 0.2],
  ["Mango", "Carboidrati", 14, 0.8, 0.4],
  ["Ciliegie", "Carboidrati", 14, 1, 0.3],
  ["Prugne (fresche)", "Carboidrati", 10, 0.7, 0.3],
  ["Fichi (freschi)", "Carboidrati", 17, 0.8, 0.3],
  ["Cachi", "Carboidrati", 16, 0.6, 0.2],
  ["Melagrana", "Carboidrati", 15, 1.7, 1.2],
  ["Mirtilli", "Carboidrati", 12, 0.7, 0.3],
  ["Albicocche Secche", "Carboidrati", 55, 3.4, 0.5],
  ["Prugne Secche", "Carboidrati", 55, 2.2, 0.4],
  ["Fichi Secchi", "Carboidrati", 58, 3.3, 0.9],
  ["Succo d'Arancia (per 100ml)", "Carboidrati", 9, 0.7, 0.2],

  // ==========================================
  // PROTEINE
  // ==========================================
  // Carni Bianche e Rosse
  ["Petto di Pollo", "Proteine", 0, 31, 3.6],
  ["Sovracosce di Pollo (senza pelle)", "Proteine", 0, 24, 8],
  ["Fesa di Tacchino", "Proteine", 0, 29, 1.5],
  ["Carne Bovina Magra (Filetto/Fesa)", "Proteine", 0, 22, 3],
  ["Macinato di Manzo (Magro 5%)", "Proteine", 0, 21, 5],
  ["Hamburger di Manzo", "Proteine", 0, 20, 15],
  ["Vitello (Tagli magri)", "Proteine", 0, 20, 2.5],
  ["Maiale (Arista magra/Filetto)", "Proteine", 0, 22, 4],
  ["Carne di Cavallo", "Proteine", 0, 21, 4.5],
  ["Carne di Coniglio", "Proteine", 0, 20, 4],
  ["Macinato di Pollo / Tacchino", "Proteine", 0, 20, 7],
  ["Macinato di Manzo (15%)", "Proteine", 0, 19, 15],
  ["Agnello (tagli magri)", "Proteine", 0, 20, 5],
  ["Fegato di Vitello", "Proteine", 4, 20, 5],
  // Affettati
  ["Bresaola", "Proteine", 0, 33, 2.6],
  ["Prosciutto Crudo (sgrassato)", "Proteine", 0, 28, 5],
  ["Prosciutto Cotto (Alta qualità)", "Proteine", 1, 20, 6],
  ["Fesa di Tacchino/Pollo (a fette)", "Proteine", 1, 24, 1.5],
  ["Speck (sgrassato)", "Proteine", 0, 28, 10],
  ["Prosciutto Crudo (con grasso)", "Proteine", 0, 25, 18],
  // Pesce
  ["Tonno Naturale (sgocciolato)", "Proteine", 0, 25, 1],
  ["Tonno Sott'olio (sgocciolato)", "Proteine", 0, 26, 8],
  ["Salmone Fresco", "Proteine", 0, 20, 13],
  ["Salmone Affumicato", "Proteine", 0, 25, 4.5],
  ["Merluzzo / Nasello", "Proteine", 0, 18, 0.7],
  ["Branzino / Spigola", "Proteine", 0, 19, 3],
  ["Orata", "Proteine", 0, 20, 4],
  ["Pesce Spada", "Proteine", 0, 19, 4],
  ["Sgombro", "Proteine", 0, 19, 11],
  ["Sarde / Alici", "Proteine", 0, 20, 4],
  ["Gamberi / Mazzancolle", "Proteine", 0, 18, 1],
  ["Calamari / Seppie", "Proteine", 1, 15, 1.5],
  ["Polpo", "Proteine", 1, 15, 1],
  ["Tonno Fresco", "Proteine", 0, 24, 5],
  ["Trota", "Proteine", 0, 20, 3.5],
  ["Platessa / Sogliola", "Proteine", 0, 17, 1.5],
  ["Baccalà (ammollato)", "Proteine", 0, 21, 0.7],
  ["Cozze (sgusciate)", "Proteine", 3.4, 12, 2.7],
  ["Vongole (sgusciate)", "Proteine", 2.2, 10, 2.5],
  // Uova e Latticini
  ["Uova Intere", "Proteine", 0.7, 13, 9.5],
  ["Albume d'Uovo", "Proteine", 0.7, 11, 0.2],
  ["Yogurt Greco 0%", "Proteine", 3.5, 10, 0.2],
  ["Yogurt Greco 2%", "Proteine", 3.5, 10, 2],
  ["Yogurt Greco 5%", "Proteine", 3.5, 9, 5],
  ["Skyr", "Proteine", 4, 11, 0.2],
  ["Fiocchi di Latte", "Proteine", 2.5, 12, 4.5],
  ["Ricotta Vaccina", "Proteine", 3.5, 9, 11],
  ["Parmigiano Reggiano / Grana", "Proteine", 0, 33, 28],
  ["Mozzarella Light", "Proteine", 1, 18, 8],
  ["Feta", "Proteine", 1.5, 14, 21],
  ["Latte Scremato (per 100ml)", "Proteine", 5, 3.4, 0.2],
  ["Latte Parz. Scremato (per 100ml)", "Proteine", 5, 3.3, 1.6],
  ["Latte Intero (per 100ml)", "Proteine", 4.9, 3.3, 3.6],
  ["Kefir (per 100ml)", "Proteine", 4, 3.4, 2],
  ["Bevanda di Soia (per 100ml)", "Proteine", 0.7, 3, 1.8],
  ["Yogurt Bianco Magro", "Proteine", 5, 4, 0.5],
  ["Yogurt Proteico", "Proteine", 4, 10, 0.2],
  ["Budino Proteico", "Proteine", 6, 10, 1.5],
  ["Quark Magro", "Proteine", 4, 12, 0.2],
  ["Mozzarella Vaccina", "Proteine", 0.7, 18, 19],
  ["Mozzarella di Bufala", "Proteine", 0.4, 17, 24],
  ["Scamorza", "Proteine", 1, 25, 25],
  ["Emmental", "Proteine", 0, 28, 30],
  ["Pecorino Romano", "Proteine", 0, 26, 32],
  // Alternative Vegetali e Integrazione
  ["Tofu", "Proteine", 2, 16, 8.5],
  ["Seitan", "Proteine", 8, 36, 2],
  ["Tempeh", "Proteine", 7, 19, 11],
  ["Soia Edamame", "Proteine", 4, 11, 5],
  ["Burger Vegetale (Soia)", "Proteine", 8, 15, 10],
  ["Proteine in Polvere (Whey)", "Proteine", 6, 80, 6],
  ["Proteine Vegane (Pisello/Riso)", "Proteine", 5, 75, 6],
  ["Proteine Isolate (Whey Isolate)", "Proteine", 2, 88, 1],
  ["Caseine in Polvere", "Proteine", 5, 78, 1.5],
  ["Barretta Proteica", "Proteine", 30, 33, 13],
  ["Lupini (in salamoia)", "Proteine", 7, 16, 2.4],
  ["Soia Texturizzata (secca)", "Proteine", 15, 50, 1.5],

  // ==========================================
  // GRASSI
  // ==========================================
  // Oli e Burri
  ["Olio Extravergine (EVO)", "Grassi", 0, 0, 100],
  ["Olio di Semi (Girasole/Arachidi)", "Grassi", 0, 0, 100],
  ["Olio di Cocco", "Grassi", 0, 0, 100],
  ["Burro Classico", "Grassi", 1, 0.9, 81],
  ["Burro Chiarificato (Ghee)", "Grassi", 0, 0.3, 99],
  ["Olio di Semi di Lino", "Grassi", 0, 0, 100],
  ["Panna Fresca (35%)", "Grassi", 3, 2.2, 35],
  ["Panna da Cucina", "Grassi", 4, 2.6, 20],
  ["Mascarpone", "Grassi", 4, 5, 44],
  ["Maionese", "Grassi", 1.5, 1.2, 75],
  // Frutta Secca (Noci e Semi)
  ["Mandorle", "Grassi", 5, 21, 50],
  ["Noci (Sgusciate)", "Grassi", 5, 15, 65],
  ["Nocciole", "Grassi", 6, 14, 61],
  ["Arachidi (non salate)", "Grassi", 8, 26, 49],
  ["Pistacchi", "Grassi", 16, 20, 45],
  ["Anacardi", "Grassi", 27, 18, 44],
  ["Noci Macadamia", "Grassi", 5, 8, 76],
  ["Noci Pecan", "Grassi", 4, 9, 72],
  ["Pinoli", "Grassi", 9, 14, 68],
  ["Semi di Chia", "Grassi", 8, 17, 31],
  ["Semi di Lino", "Grassi", 2, 18, 42],
  ["Semi di Zucca", "Grassi", 5, 30, 49],
  ["Semi di Girasole", "Grassi", 11, 21, 51],
  ["Noci del Brasile", "Grassi", 4, 14, 67],
  ["Semi di Sesamo", "Grassi", 12, 18, 50],
  ["Semi di Canapa (decorticati)", "Grassi", 5, 32, 49],
  // Creme, Cioccolato e Altro
  ["Burro d'Arachidi (100%)", "Grassi", 11, 26, 50],
  ["Burro di Mandorle (100%)", "Grassi", 7, 21, 53],
  ["Tahina (Crema di Sesamo)", "Grassi", 11, 17, 53],
  ["Cioccolato Fondente 85%", "Grassi", 19, 12, 46],
  ["Cioccolato Fondente 99%", "Grassi", 8, 14, 50],
  ["Avocado", "Grassi", 2, 2, 15],
  ["Olive Verdi", "Grassi", 1, 1, 15],
  ["Olive Nere", "Grassi", 1, 1.5, 25],
  ["Cocco essiccato (Rapè)", "Grassi", 7, 7, 65],
  ["Cocco Fresco", "Grassi", 6, 3.3, 33],
  ["Crema di Nocciole (100%)", "Grassi", 6, 15, 62],
  ["Crema di Pistacchio (100%)", "Grassi", 14, 20, 50],
  ["Cioccolato Fondente 70%", "Grassi", 33, 9, 41],
  ["Tuorlo d'Uovo", "Grassi", 1, 16, 27],

  // ==========================================
  // VERDURE (libere nelle sostituzioni, ma contate nei totali)
  // ==========================================
  ["Asparagi", "Verdure", 3, 3, 0.2],
  ["Broccoli", "Verdure", 4, 2.8, 0.4],
  ["Carciofi", "Verdure", 2.5, 2.7, 0.2],
  ["Carote", "Verdure", 7.6, 1.1, 0.2],
  ["Cavolfiore", "Verdure", 2.7, 3.2, 0.2],
  ["Cavolini di Bruxelles", "Verdure", 4.2, 4.2, 0.5],
  ["Cetrioli", "Verdure", 1.8, 0.7, 0.5],
  ["Cipolle", "Verdure", 5.7, 1, 0.1],
  ["Fagiolini (Cornetti)", "Verdure", 2.4, 2.1, 0.1],
  ["Finocchi", "Verdure", 1, 1.2, 0],
  ["Funghi (Champignon/Porcini)", "Verdure", 0.5, 3.3, 0.3],
  ["Insalata Mista / Lattuga", "Verdure", 2.2, 1.8, 0.4],
  ["Melanzane", "Verdure", 2.6, 1.1, 0.1],
  ["Peperoni", "Verdure", 4.2, 0.9, 0.3],
  ["Pomodori / Pomodorini", "Verdure", 3, 1, 0.2],
  ["Radicchio", "Verdure", 1.6, 1.4, 0.1],
  ["Rucola", "Verdure", 3.9, 2.6, 0.3],
  ["Sedano", "Verdure", 2.4, 2.3, 0.2],
  ["Spinaci / Bieta", "Verdure", 2.9, 3.4, 0.7],
  ["Zucca", "Verdure", 3.5, 1.1, 0.1],
  ["Zucchine", "Verdure", 1.4, 1.3, 0.1],
  ["Cavolo Nero / Verza", "Verdure", 3, 2.1, 0.1],
  ["Cavolo Cappuccio", "Verdure", 3.5, 1.3, 0.1],
  ["Cime di Rapa / Friarielli", "Verdure", 2, 2.9, 0.3],
  ["Cicoria / Catalogna", "Verdure", 0.7, 1.4, 0.2],
  ["Scarola / Indivia", "Verdure", 1.7, 1.2, 0.2],
  ["Valeriana / Songino", "Verdure", 1.5, 2, 0.4],
  ["Porri", "Verdure", 5.2, 2.1, 0.1],
  ["Ravanelli", "Verdure", 1.8, 0.8, 0.1],
  ["Germogli di Soia", "Verdure", 4, 3, 0.2],
  ["Crauti", "Verdure", 1.5, 1, 0.1],
  ["Sedano Rapa", "Verdure", 5, 1.5, 0.3],
  ["Passata di Pomodoro", "Verdure", 4.5, 1.4, 0.2]
];

const MAIN_MACRO_KEY = { Carboidrati: 'c', Proteine: 'p', Grassi: 'f' };

const PRESET_FOODS = FOOD_TABLE.map(([name, category, c, p, f]) => ({
  name,
  category,
  c,
  p,
  f,
  // grammi del macro principale per 100 g (0 per le verdure, che sono "libere")
  macroValue: MAIN_MACRO_KEY[category] ? { c, p, f }[MAIN_MACRO_KEY[category]] : 0
}));
