// Database alimenti predefinito: grammi del macro principale per 100 g di prodotto.
const PRESET_FOODS = [
  // ==========================================
  // CARBOIDRATI (Grammi di Carbo su 100g)
  // ==========================================
  // Pasta e Gnocchi
  { name: "Pasta di Semola", category: "Carboidrati", macroValue: 73 },
  { name: "Pasta Integrale", category: "Carboidrati", macroValue: 65 },
  { name: "Pasta all'Uovo", category: "Carboidrati", macroValue: 68 },
  { name: "Pasta di Riso", category: "Carboidrati", macroValue: 80 },
  { name: "Pasta di Mais", category: "Carboidrati", macroValue: 79 },
  { name: "Pasta di Farro", category: "Carboidrati", macroValue: 67 },
  { name: "Pasta di Lenticchie/Piselli", category: "Carboidrati", macroValue: 50 },
  { name: "Gnocchi di Patate (confezionati)", category: "Carboidrati", macroValue: 20 },
  // Riso e Cereali
  { name: "Riso Basmati", category: "Carboidrati", macroValue: 78 },
  { name: "Riso Carnaroli / Arborio", category: "Carboidrati", macroValue: 80 },
  { name: "Riso Integrale", category: "Carboidrati", macroValue: 74 },
  { name: "Riso Venere (Nero)", category: "Carboidrati", macroValue: 72 },
  { name: "Riso Rosso", category: "Carboidrati", macroValue: 74 },
  { name: "Avena (Fiocchi)", category: "Carboidrati", macroValue: 60 },
  { name: "Farina di Avena", category: "Carboidrati", macroValue: 60 },
  { name: "Farro Perlato", category: "Carboidrati", macroValue: 67 },
  { name: "Orzo Perlato", category: "Carboidrati", macroValue: 70 },
  { name: "Quinoa", category: "Carboidrati", macroValue: 64 },
  { name: "Cous Cous", category: "Carboidrati", macroValue: 77 },
  { name: "Grano Saraceno", category: "Carboidrati", macroValue: 71 },
  { name: "Polenta (Farina di Mais)", category: "Carboidrati", macroValue: 75 },
  { name: "Cornflakes (classici)", category: "Carboidrati", macroValue: 81 },
  // Pane e Sostituti
  { name: "Pane Bianco", category: "Carboidrati", macroValue: 49 },
  { name: "Pane Integrale", category: "Carboidrati", macroValue: 43 },
  { name: "Pane di Segale", category: "Carboidrati", macroValue: 48 },
  { name: "Pane Bauletto (industriale)", category: "Carboidrati", macroValue: 50 },
  { name: "Piadina Romagnola", category: "Carboidrati", macroValue: 50 },
  { name: "Gallette di Mais", category: "Carboidrati", macroValue: 77 },
  { name: "Gallette di Riso", category: "Carboidrati", macroValue: 81 },
  { name: "Fette Biscottate classiche", category: "Carboidrati", macroValue: 72 },
  { name: "Fette Biscottate integrali", category: "Carboidrati", macroValue: 67 },
  { name: "Taralli", category: "Carboidrati", macroValue: 60 },
  { name: "Grissini", category: "Carboidrati", macroValue: 68 },
  { name: "Crackers", category: "Carboidrati", macroValue: 70 },
  // Tuberi (Patate)
  { name: "Patate Classiche (con buccia)", category: "Carboidrati", macroValue: 17 },
  { name: "Patate Novelle", category: "Carboidrati", macroValue: 15 },
  { name: "Patate Dolci (Americane)", category: "Carboidrati", macroValue: 20 },
  { name: "Patate Rosse", category: "Carboidrati", macroValue: 16 },
  { name: "Manioca / Yuca", category: "Carboidrati", macroValue: 38 },
  // Legumi Secchi (Pesati a crudo)
  { name: "Ceci (Secchi)", category: "Carboidrati", macroValue: 47 },
  { name: "Lenticchie (Secche)", category: "Carboidrati", macroValue: 51 },
  { name: "Fagioli Borlotti/Cannellini (Secchi)", category: "Carboidrati", macroValue: 45 },
  { name: "Piselli (Secchi)", category: "Carboidrati", macroValue: 45 },
  // Legumi Cotti/In scatola (Sgocciolati)
  { name: "Ceci (In scatola)", category: "Carboidrati", macroValue: 15 },
  { name: "Lenticchie (In scatola)", category: "Carboidrati", macroValue: 12 },
  { name: "Fagioli (In scatola)", category: "Carboidrati", macroValue: 14 },
  { name: "Piselli (Surgelati/Scatola)", category: "Carboidrati", macroValue: 10 },
  // Frutta (Zuccheri/Carbo)
  { name: "Banana", category: "Carboidrati", macroValue: 23 },
  { name: "Mela", category: "Carboidrati", macroValue: 14 },
  { name: "Pera", category: "Carboidrati", macroValue: 15 },
  { name: "Kiwi", category: "Carboidrati", macroValue: 15 },
  { name: "Uva", category: "Carboidrati", macroValue: 18 },
  { name: "Frutti di Bosco / Fragole", category: "Carboidrati", macroValue: 8 },
  { name: "Arancia / Mandarino", category: "Carboidrati", macroValue: 9 },
  { name: "Datteri secchi", category: "Carboidrati", macroValue: 75 },
  { name: "Uvetta / Frutta disidratata", category: "Carboidrati", macroValue: 79 },
  
  // ==========================================
  // PROTEINE (Grammi di Proteine su 100g)
  // ==========================================
  // Carni Bianche e Rosse
  { name: "Petto di Pollo", category: "Proteine", macroValue: 31 },
  { name: "Sovracosce di Pollo (senza pelle)", category: "Proteine", macroValue: 24 },
  { name: "Fesa di Tacchino", category: "Proteine", macroValue: 29 },
  { name: "Carne Bovina Magra (Filetto/Fesa)", category: "Proteine", macroValue: 22 },
  { name: "Macinato di Manzo (Magro 5%)", category: "Proteine", macroValue: 21 },
  { name: "Hamburger di Manzo", category: "Proteine", macroValue: 20 },
  { name: "Vitello (Tagli magri)", category: "Proteine", macroValue: 20 },
  { name: "Maiale (Arista magra/Filetto)", category: "Proteine", macroValue: 22 },
  { name: "Carne di Cavallo", category: "Proteine", macroValue: 21 },
  { name: "Carne di Coniglio", category: "Proteine", macroValue: 20 },
  // Affettati
  { name: "Bresaola", category: "Proteine", macroValue: 33 },
  { name: "Prosciutto Crudo (sgrassato)", category: "Proteine", macroValue: 28 },
  { name: "Prosciutto Cotto (Alta qualità)", category: "Proteine", macroValue: 20 },
  { name: "Fesa di Tacchino/Pollo (a fette)", category: "Proteine", macroValue: 24 },
  { name: "Speck (sgrassato)", category: "Proteine", macroValue: 28 },
  // Pesce
  { name: "Tonno Naturale (sgocciolato)", category: "Proteine", macroValue: 25 },
  { name: "Tonno Sott'olio (sgocciolato)", category: "Proteine", macroValue: 26 },
  { name: "Salmone Fresco", category: "Proteine", macroValue: 20 },
  { name: "Salmone Affumicato", category: "Proteine", macroValue: 25 },
  { name: "Merluzzo / Nasello", category: "Proteine", macroValue: 18 },
  { name: "Branzino / Spigola", category: "Proteine", macroValue: 19 },
  { name: "Orata", category: "Proteine", macroValue: 20 },
  { name: "Pesce Spada", category: "Proteine", macroValue: 19 },
  { name: "Sgombro", category: "Proteine", macroValue: 19 },
  { name: "Sarde / Alici", category: "Proteine", macroValue: 20 },
  { name: "Gamberi / Mazzancolle", category: "Proteine", macroValue: 18 },
  { name: "Calamari / Seppie", category: "Proteine", macroValue: 15 },
  { name: "Polpo", category: "Proteine", macroValue: 15 },
  // Uova e Latticini
  { name: "Uova Intere", category: "Proteine", macroValue: 13 },
  { name: "Albume d'Uovo", category: "Proteine", macroValue: 11 },
  { name: "Yogurt Greco 0%", category: "Proteine", macroValue: 10 },
  { name: "Yogurt Greco 2%", category: "Proteine", macroValue: 10 },
  { name: "Yogurt Greco 5%", category: "Proteine", macroValue: 9 },
  { name: "Skyr", category: "Proteine", macroValue: 11 },
  { name: "Fiocchi di Latte", category: "Proteine", macroValue: 12 },
  { name: "Ricotta Vaccina", category: "Proteine", macroValue: 9 },
  { name: "Parmigiano Reggiano / Grana", category: "Proteine", macroValue: 33 },
  { name: "Mozzarella Light", category: "Proteine", macroValue: 18 },
  { name: "Feta", category: "Proteine", macroValue: 14 },
  { name: "Latte Scremato (per 100ml)", category: "Proteine", macroValue: 3.4 },
  { name: "Latte Parz. Scremato (per 100ml)", category: "Proteine", macroValue: 3.3 },
  // Alternative Vegetali e Integrazione
  { name: "Tofu", category: "Proteine", macroValue: 16 },
  { name: "Seitan", category: "Proteine", macroValue: 36 },
  { name: "Tempeh", category: "Proteine", macroValue: 19 },
  { name: "Soia Edamame", category: "Proteine", macroValue: 11 },
  { name: "Burger Vegetale (Soia)", category: "Proteine", macroValue: 15 },
  { name: "Proteine in Polvere (Whey)", category: "Proteine", macroValue: 80 },
  { name: "Proteine Vegane (Pisello/Riso)", category: "Proteine", macroValue: 75 },
  
  // ==========================================
  // GRASSI (Grammi di Grassi su 100g)
  // ==========================================
  // Oli e Burri
  { name: "Olio Extravergine (EVO)", category: "Grassi", macroValue: 100 },
  { name: "Olio di Semi (Girasole/Arachidi)", category: "Grassi", macroValue: 100 },
  { name: "Olio di Cocco", category: "Grassi", macroValue: 100 },
  { name: "Burro Classico", category: "Grassi", macroValue: 81 },
  { name: "Burro Chiarificato (Ghee)", category: "Grassi", macroValue: 99 },
  // Frutta Secca (Noci e Semi)
  { name: "Mandorle", category: "Grassi", macroValue: 50 },
  { name: "Noci (Sgusciate)", category: "Grassi", macroValue: 65 },
  { name: "Nocciole", category: "Grassi", macroValue: 61 },
  { name: "Arachidi (non salate)", category: "Grassi", macroValue: 49 },
  { name: "Pistacchi", category: "Grassi", macroValue: 45 },
  { name: "Anacardi", category: "Grassi", macroValue: 44 },
  { name: "Noci Macadamia", category: "Grassi", macroValue: 76 },
  { name: "Noci Pecan", category: "Grassi", macroValue: 72 },
  { name: "Pinoli", category: "Grassi", macroValue: 68 },
  { name: "Semi di Chia", category: "Grassi", macroValue: 31 },
  { name: "Semi di Lino", category: "Grassi", macroValue: 42 },
  { name: "Semi di Zucca", category: "Grassi", macroValue: 49 },
  { name: "Semi di Girasole", category: "Grassi", macroValue: 51 },
  // Creme, Cioccolato e Altro
  { name: "Burro d'Arachidi (100%)", category: "Grassi", macroValue: 50 },
  { name: "Burro di Mandorle (100%)", category: "Grassi", macroValue: 53 },
  { name: "Tahina (Crema di Sesamo)", category: "Grassi", macroValue: 53 },
  { name: "Cioccolato Fondente 85%", category: "Grassi", macroValue: 46 },
  { name: "Cioccolato Fondente 99%", category: "Grassi", macroValue: 50 },
  { name: "Avocado", category: "Grassi", macroValue: 15 },
  { name: "Olive Verdi", category: "Grassi", macroValue: 15 },
  { name: "Olive Nere", category: "Grassi", macroValue: 25 },
  { name: "Cocco essiccato (Rapè)", category: "Grassi", macroValue: 65 },
  
  // ==========================================
  // VERDURE (Gestite liberamente: 0 macro)
  // ==========================================
  { name: "Asparagi", category: "Verdure", macroValue: 0 },
  { name: "Broccoli", category: "Verdure", macroValue: 0 },
  { name: "Carciofi", category: "Verdure", macroValue: 0 },
  { name: "Carote", category: "Verdure", macroValue: 0 },
  { name: "Cavolfiore", category: "Verdure", macroValue: 0 },
  { name: "Cavolini di Bruxelles", category: "Verdure", macroValue: 0 },
  { name: "Cetrioli", category: "Verdure", macroValue: 0 },
  { name: "Cipolle", category: "Verdure", macroValue: 0 },
  { name: "Fagiolini (Cornetti)", category: "Verdure", macroValue: 0 },
  { name: "Finocchi", category: "Verdure", macroValue: 0 },
  { name: "Funghi (Champignon/Porcini)", category: "Verdure", macroValue: 0 },
  { name: "Insalata Mista / Lattuga", category: "Verdure", macroValue: 0 },
  { name: "Melanzane", category: "Verdure", macroValue: 0 },
  { name: "Peperoni", category: "Verdure", macroValue: 0 },
  { name: "Pomodori / Pomodorini", category: "Verdure", macroValue: 0 },
  { name: "Radicchio", category: "Verdure", macroValue: 0 },
  { name: "Rucola", category: "Verdure", macroValue: 0 },
  { name: "Sedano", category: "Verdure", macroValue: 0 },
  { name: "Spinaci / Bieta", category: "Verdure", macroValue: 0 },
  { name: "Zucca", category: "Verdure", macroValue: 0 },
  { name: "Zucchine", category: "Verdure", macroValue: 0 }
];
